### ISSUE TITLE
IDE Shows false errors regards codebase under Ventura MacOS

### ISSUE THREAD

**Issue by Gardosen** [cypress-io/cypress-example-kitchensink#764] opened 2023-11-07 08:23 UTC
Hello Everyone,

The Following Issue happens for me

Background:
  Given I am using Cypress
  And I use an IDE from Jetbrains

Scenario Outline:
   When I work on a "<device>" with "<macosVersion>"
   And I create a new Cypress javascript examples Project with Cypress version "<cypressVersion>"
   And I go to the commands.js
   And I add a new command called "getElement"
   Then I do not see a warning in the IDE

  Examples:
  | device                          | macosVersion     |
  | macbook pro m1 pro  | Monterey 12.6.1  |
  | macbook pro m2 pro  | Ventura 13.6.      |

Scenario 1: pass
Scenario 2: fail on "Then I do not see a warning in the IDE"
See screenshot
<img width="1267" alt="Screenshot 2023-11-06 at 18 07 06" src="https://github.com/cypress-io/cypress-example-kitchensink/assets/415867/6c3fb692-4914-4381-bb53-e727c0b53120">

Note: the cucumber gherkin style is just a little joke ;) the issue is what i describe ^^
I am able to reproduce this with the basice Cypress example the IDE is creating.

**Comment by MikeMcC399** [comment] 2023-11-07 08:33
@Gardosen

This looks like the issue you also raised in [Discord](https://discord.com/channels/755913899261296641/1171134262322409502/1171134262322409502).

This repository is not the right place for your issue. If you believe that it is a bug in Cypress, then the issue would need to go into https://github.com/cypress-io/cypress/issues.

I suggest to close it here and re-submit in https://github.com/cypress-io/cypress/issues with the details that are requested there.
It is also highly advisable to submit a complete minimum reproducible example as part of the issue.

**Comment by Gardosen** [comment] 2023-11-07 10:08
oh my god, i am so sorry. i actually wanted to open it under cypress-io. o.o

thank you for pointing this out.

**Comment by MikeMcC399** [comment] 2023-11-09 11:51
@Gardosen 

You should use the close button down below ⬇️ to close this issue.

**Closed** 2023-11-15 16:53 UTC
